### ISSUE TITLE
Prints sugguestion for cd alias when it shouldn't

### ISSUE THREAD

**Issue by CodingPenguin1** [paysonwallach/fish-you-should-use#1]
I have these aliases in my config.fish:
```
alias ..="cd .."
alias ...="cd ../.."
alias .3="cd ../../.."
alias .4="cd ../../../.."
alias .5="cd ../../../../.."
```

When I run `cd Documents`, it outputs
```
Found existing alias for "cd ..".
You should use: ".."
```

I do not believe this to be expected behavior

**Comment by paysonwallach** [comment]
Thank you for the issue! It is definitely not expected behaviour. I've just released version 1.0.2 which should correct the issue, though let me know if it does not otherwise.
