### ISSUE TITLE
set YSU_MESSAGE_POSITION "before" does nothing

### ISSUE THREAD

**Issue by CodingPenguin1** [paysonwallach/fish-you-should-use#2]
Setting `YSU_MESSAGE_POSITION` to "before" in my `config.fish` 

`set YSU_MESSAGE_POSITION "before"`

does not output the message before the command is executed

**Comment by paysonwallach** [comment]
The `YSU` prefix in the variable name is proceeded by two underscores, not one, i.e. `YSU__MESSAGE_POSITION`
